### ISSUE TITLE
Example of incorrect parsing?

### ISSUE THREAD

**Issue by VitorCBSB** [pbrisbin/hs-shellwords#3]
Hey, I've been looking for a library to help me parse `pkg-config` outputs and this seems like a good candidate, but it seems to be failing for my use case? Let me know if it's somehow badly formed or something, I'm not really familiar with shell rules:

```
Prelude> let a = "-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -ltag\n"
Prelude> a
"-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -ltag\n"
Prelude> import ShellWords
Prelude ShellWords> parse a
Right ["-LC:/Users/Vitor\\","Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib","-ltag\n"]
Prelude ShellWords> 
```

The `-L` argument is supposed to be one string, followed by `-ltag` (should the `\n` be there?), but it's being split after the supposedly escaped space character.

**Comment by pbrisbin** [comment]
Hi, thanks for reporting!

I think the trailing newline is not an Issue with the library: it's respecting the input given, and it's up to you to chomp that off before parsing, IMO. Please let me know if you disagree (and why).

The other issue seems to be that it doesn't know about the escaped space and is treating it as if it separates arguments. I can probably look into that next week; I agree it looks like a bug.

**Comment by VitorCBSB** [comment]
I don't know what the expected behavior for a trailing newline is. I kinda expect it to be treated like a common whitespace would, being removed from the result, but if you feel otherwise, it's up to you.

**Comment by pbrisbin** [comment]
Yeah that's reasonable, I'll give it some thought.

**Comment by pbrisbin** [comment]
I checked this against the python library this is a port of and it handles thing as you expected, it seems:

```
>>> from shellwords import ShellWords
>>> s = ShellWords()
>>> a = "-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -ltag\n"
>>> s.parse(a)
['-LC:/Users/Vitor Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib', '-ltag']
```

I'll address them both!

FWIW, including whitespace in the input is possible but requires careful quoting or escaping:

```
>>> a = "-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -l 'tag\n'"
>>> s.parse(a)
['-LC:/Users/Vitor Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib', '-l', 'tag\n']
>>> a = "-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -l tag\\n"
>>> s.parse(a)
['-LC:/Users/Vitor Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib', '-l', 'tagn']
>>> a = "-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -l \"tag\\n\""
>>> s.parse(a)
['-LC:/Users/Vitor Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib', '-l', 'tagn']
>>> a = "-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -l \"tag\\\n\""
>>> s.parse(a)
['-LC:/Users/Vitor Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib', '-l', 'tag\n']
>>> a = "-LC:/Users/Vitor\\ Coimbra/AppData/Local/Programs/stack/x86_64-windows/msys2-20150512/mingw64/lib -l tag\\\n"
>>> s.parse(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/shellwords/__init__.py", line 111, in parse
    raise Exception("invalid command line string")
Exception: invalid command line string
```

I'll try to capture this in the test cases.

**Comment by VitorCBSB** [comment]
Nice! Thanks for solving this. I'll check it out as soon as I can. :)
